services:
  mongodb:
    image: mongo:8
    container_name: trading-api-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: trading_api
    volumes:
      - trading_api_mongodb_data:/data/db

volumes:
  trading_api_mongodb_data: